# Generated by Django 4.1 on 2022-08-08 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BirthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasteCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisabilityCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BirthCertificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpanel.birthcertificate",
                    ),
                ),
                (
                    "CasteCertificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpanel.castecertificate",
                    ),
                ),
                (
                    "DisabilityCertificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpanel.disabilitycertificate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SportsCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField()),
                (
                    "documentField",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpanel.documentmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalityCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigrationCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JEEmarksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JEEallotmentLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomicileCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="DomicileCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.domicilecertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="HSC",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.hsc"
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="IncomeCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.incomecertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="JEEallotmentLetter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.jeeallotmentletter",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="JEEmarksheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.jeemarksheet",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="MedicalCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.medicalcertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="MigrationCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.migrationcertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="NationalityCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.nationalitycertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="PAN",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.pan"
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="Passport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.passport"
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="SSC",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.ssc"
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="SportsCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.sportscertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="TransferCertificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.transfercertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
