# Generated by Django 4.1 on 2022-08-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BirthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CasteCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DisabilityCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomicileCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Form", max_length=255, verbose_name="Form Title"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="IncomeCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="JEEallotmentLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="JEEmarksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MigrationCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NationalityCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technique",
                    models.CharField(
                        choices=[
                            ("mcq_one", "MCQ with single possible answer"),
                            ("text", "Text based answer"),
                            ("file_upload", "File Upload answer"),
                        ],
                        max_length=55,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Created"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active Status"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SportsCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SSC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileUploadAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adminpanel.answer",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="my_documents")),
            ],
            options={
                "abstract": False,
            },
            bases=("adminpanel.answer",),
        ),
        migrations.CreateModel(
            name="McqOneAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adminpanel.answer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("adminpanel.answer",),
        ),
        migrations.CreateModel(
            name="TextAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adminpanel.answer",
                    ),
                ),
                ("answer_text", models.TextField(max_length=1000)),
            ],
            options={
                "abstract": False,
            },
            bases=("adminpanel.answer",),
        ),
    ]
