# Generated by Django 4.1 on 2022-08-26 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfercertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="ssc",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sportscertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="adminpanel.form",
                verbose_name="Form.id",
            ),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="documentField",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.documentmodel",
            ),
        ),
        migrations.AddField(
            model_name="personaldetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="passport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="nationalitycertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="migrationcertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="medicalcertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="jeemarksheet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="jeeallotmentletter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="incomecertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hsc",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="domicilecertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="AdhaarFile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.adhaarfile",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="BirthCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.birthcertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="CasteCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.castecertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="DisabilityCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.disabilitycertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="DomicileCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.domicilecertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="HSC",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.hsc",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="IncomeCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.incomecertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="JEEallotmentLetter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.jeeallotmentletter",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="JEEmarksheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.jeemarksheet",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="MedicalCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.medicalcertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="MigrationCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.migrationcertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="NationalityCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.nationalitycertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="PAN",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.pan",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="Passport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.passport",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="SSC",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.ssc",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="SportsCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.sportscertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="TransferCertificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.transfercertificate",
            ),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="disabilitycertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.question"
            ),
        ),
        migrations.AddField(
            model_name="castecertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="birthcertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="adminpanel.question",
            ),
        ),
        migrations.AddField(
            model_name="adhaarfile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mcqoneanswer",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.choice"
            ),
        ),
    ]
