# Generated by Django 3.2.19 on 2023-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20230510_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhaarfile',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='castecertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='disabilitycertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='domicilecertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='hsc',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='jeeallotmentletter',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='jeemarksheet',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='migrationcertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='nationalitycertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='pan',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='passport',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='sportscertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='ssc',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='File',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
