# Generated by Django 3.2.19 on 2023-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20230510_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
