# Generated by Django 4.1 on 2022-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0005_alter_documentmodel_hsc_alter_documentmodel_ssc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="castecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="disabilitycertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="domicilecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="fileuploadanswer",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="hsc",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="incomecertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="jeeallotmentletter",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="jeemarksheet",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="medicalcertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="migrationcertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="nationalitycertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="pan",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="passport",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="sportscertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="ssc",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
        migrations.AlterField(
            model_name="transfercertificate",
            name="File",
            field=models.FileField(blank=True, upload_to="docs"),
        ),
    ]
