# Generated by Django 4.1 on 2022-08-25 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adminpanel", "0006_alter_castecertificate_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adhaar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adhaar_no", models.CharField(blank=True, max_length=255)),
                ("phone_no", models.CharField(blank=True, max_length=12)),
                ("dob", models.DateField(auto_now_add=True)),
                ("gender", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AdhaarFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("File", models.FileField(blank=True, upload_to="docs")),
                ("PrivateKey", models.CharField(blank=True, max_length=500)),
                ("isVerified", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="AdhaarFile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.adhaarfile",
            ),
        ),
    ]
