# Generated by Django 4.1 on 2022-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0007_adhaar_adhaarfile_documentmodel_adhaarfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adhaar",
            name="phone_no",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
