# Generated by Django 4.1 on 2022-08-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0008_alter_adhaar_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreVerifiedAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="adminpanel.answer",
                    ),
                ),
                ("doc_id", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("adminpanel.answer",),
        ),
        migrations.AlterField(
            model_name="question",
            name="technique",
            field=models.CharField(
                choices=[
                    ("mcq_one", "MCQ with single possible answer"),
                    ("text", "Text based answer"),
                    ("file_upload", "File Upload answer"),
                    ("pre_verified", "Auto Upload answer"),
                ],
                max_length=55,
            ),
        ),
    ]
