# Generated by Django 4.1 on 2022-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitpreverifiedquestion",
            name="form",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
