# Generated by Django 4.1 on 2022-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0002_submitpreverifiedquestion_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitpreverifiedquestion",
            name="question",
            field=models.IntegerField(),
        ),
    ]
