# Generated by Django 4.1 on 2022-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0003_alter_submitpreverifiedquestion_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submitpreverifiedquestion",
            name="answer",
        ),
        migrations.AddField(
            model_name="submitpreverifiedquestion",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
