# Generated by Django 4.1 on 2022-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpanel", "0004_remove_submitpreverifiedquestion_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitpreverifiedquestion",
            name="file_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
