# Generated by Django 3.2.19 on 2023-05-11 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_personaldetails_age'),
        ('userpanel', '0006_submitfilequestion_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitfilequestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.form'),
        ),
        migrations.AlterField(
            model_name='submitpreverifiedquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.form'),
        ),
    ]
