# Generated by Django 3.2.19 on 2023-05-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_personaldetails_age'),
        ('userpanel', '0007_auto_20230511_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittextquestion',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.form'),
            preserve_default=False,
        ),
    ]
