# Generated by Django 4.1 on 2022-08-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_adhaar_no_user_phone_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_no",
        ),
    ]
