# Generated by Django 4.1 on 2022-08-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_user_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
