# Generated by Django 4.1 on 2022-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_user_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
