# Generated by Django 4.1 on 2022-08-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_verifyotp_remove_user_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="verifyOTP",
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
